apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: makeshapp1
  name: makeshapp1
  namespace: makesh-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeshapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: makeshapp1
    spec:
      containers:
      - image: makeshdocker/makeshmobi:appv1
        name: makeshmobi
        ports:
        - containerPort: 80
        resources: {}
        
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: makeshsvc1
  name: makeshsvc1
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: makeshapp1
  type: NodePort
status:
  loadBalancer: {}
        
status: {}
